In [5]:
import numpy as np

In [6]:
x = np.array([-1.0, 1.0, 2.0])

# Sigmoid

In [7]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

sigmoid(x)

array([0.26894142, 0.73105858, 0.88079708])

# ReLU

In [8]:
def ReLU(x):
    return np.maximum(0,x)

ReLU(x)

array([0., 1., 2.])

In [10]:
# 위와 아래는 무슨 차이인가?

In [9]:
def ReLU(x):
    mask = (x<=0)
    out = x.copy()
    out[mask] = 0
    
    return out
ReLU(x)

array([0., 1., 2.])