In [34]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [35]:
tf.random.set_seed(42)

In [36]:
h = [1,0,0,0]
e = [0,1,0,0]
l = [0,0,1,0]
o = [0,0,0,1]

In [37]:
x_data = np.array([[h]], dtype=np.float32)
x_data

array([[[1., 0., 0., 0.]]], dtype=float32)

In [38]:
x_data.shape

(1, 1, 4)

In [39]:
# sample, token, token's embedding <<<- 시험에 나온다.

In [40]:
hidden_size = 2
cell = layers.SimpleRNNCell(units = hidden_size)
rnn = layers.RNN(cell, return_sequences=True, return_state=True)
output, states =rnn(x_data)

print('x_data: {} `t shape : {}'.format(x_data,x_data.shape))
print('output: {} `t shape : {}'.format(output, output))
print('states: {} `t shape : {}'.format(states, states.shape))


x_data: [[[1. 0. 0. 0.]]] `t shape : (1, 1, 4)
output: [[[ 0.31773362 -0.11744198]]] `t shape : [[[ 0.31773362 -0.11744198]]]
states: [[ 0.31773362 -0.11744198]] `t shape : (1, 2)


In [41]:
hidden_size = 2
cell = layers.SimpleRNNCell(units = hidden_size)
rnn = layers.RNN(cell, return_sequences=True, return_state=False)
output=rnn(x_data)

print('x_data: {} `t shape : {}'.format(x_data,x_data.shape))
print('output: {} `t shape : {}'.format(output, output))
#print('states: {} `t shape : {}'.format(states, states.shape))


x_data: [[[1. 0. 0. 0.]]] `t shape : (1, 1, 4)
output: [[[0.44843182 0.251574  ]]] `t shape : [[[0.44843182 0.251574  ]]]


In [42]:
hidden_size = 2
cell = layers.SimpleRNNCell(units = hidden_size)
rnn = layers.RNN(cell, return_sequences=False, return_state=True)
output, states =rnn(x_data)

print('x_data: {} `t shape : {}'.format(x_data,x_data.shape))
print('output: {} `t shape : {}'.format(output, output))
print('states: {} `t shape : {}'.format(states, states.shape))


x_data: [[[1. 0. 0. 0.]]] `t shape : (1, 1, 4)
output: [[ 0.54152584 -0.00444528]] `t shape : [[ 0.54152584 -0.00444528]]
states: [[ 0.54152584 -0.00444528]] `t shape : (1, 2)


In [43]:
# 보통은 이렇게 합쳐서 씀
rnn = layers.SimpleRNN(units=hidden_size, return_sequences=True, return_state=True)
output, states = rnn(x_data)

print('x_data: {} `t shape : {}'.format(x_data,x_data.shape))
print('output: {} `t shape : {}'.format(output, output))
print('states: {} `t shape : {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]]] `t shape : (1, 1, 4)
output: [[[-0.12818007  0.04968958]]] `t shape : [[[-0.12818007  0.04968958]]]
states: [[-0.12818007  0.04968958]] `t shape : (1, 2)


In [44]:
x_data = np.array([[h,e,l,l,o]], dtype=np.float32)
x_data

array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]], dtype=float32)

In [45]:
x_data.shape

(1, 5, 4)

In [46]:
hidden_size = 2
rnn = layers.SimpleRNN(units=hidden_size, return_sequences=True,return_state=True)
output, states = rnn(x_data)

print('x_data: {} `t shape : {}'.format(x_data,x_data.shape))
print('output: {} `t shape : {}'.format(output, output))
print('states: {} `t shape : {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]] `t shape : (1, 5, 4)
output: [[[-0.53046876  0.57137597]
  [ 0.87748426  0.40262657]
  [-0.15409194  0.93952847]
  [ 0.764736    0.94110495]
  [-0.5227913   0.79280305]]] `t shape : [[[-0.53046876  0.57137597]
  [ 0.87748426  0.40262657]
  [-0.15409194  0.93952847]
  [ 0.764736    0.94110495]
  [-0.5227913   0.79280305]]]
states: [[-0.5227913   0.79280305]] `t shape : (1, 2)


In [47]:
x_data = np.array([[h,e,l,l,o],[e,o,l,l,l],[l,l,e,e,l]], dtype = np.float32)
x_data.shape

(3, 5, 4)

In [48]:
hidden_size = 2
rnn = layers.SimpleRNN(units=hidden_size, return_sequences=True,return_state=True)
output, states = rnn(x_data)

print('x_data: {} `t shape : {}'.format(x_data,x_data.shape))
print('output: {} `t shape : {}'.format(output, output))
print('states: {} `t shape : {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]] `t shape : (3, 5, 4)
output: [[[ 0.14876226 -0.53846276]
  [-0.14836739 -0.7307358 ]
  [-0.4311056  -0.29082945]
  [ 0.04810696 -0.3949708 ]
  [ 0.42104387 -0.33169279]]

 [[ 0.38647366 -0.7109882 ]
  [ 0.0374865  -0.13167973]
  [ 0.04029264  0.07699038]
  [ 0.23158996  0.14889458]
  [ 0.2347412   0.34022516]]

 [[ 0.17510563  0.085945  ]
  [ 0.19634894  0.27287996]
  [ 0.5360052  -0.5458496 ]
  [-0.27913758 -0.51398796]
  [-0.2099702  -0.33608466]]] `t shape : [[[ 0.14876226 -0.53846276]
  [-0.14836739 -0.7307358 ]
  [-0.4311056  -0.29082945]
  [ 0.04810696 -0.3949708 ]
  [ 0.42104387 -0.33169279]]

 [[ 0.38647366 -0.7109882 ]
  [ 0.0374865  -0.13167973]
  [ 0.04029264  0.07699038]
  [ 0.23158996  0.14889458]
  [ 0.2347412   0.34022516

In [49]:
idx2char = ['토','마','를','먹','자']

x_data = [[0,0,1,2,4,3]] # 토 토 마 를 자 먹
y_data = [[0,1,0,2,3,4]] # 토 마 토 를 먹 자
num_classes = 5
input_dim = 5
sequence_len = 6 
learning_rate = 0.1

x_one_hot = tf.keras.utils.to_categorical(x_data, num_classes=num_classes)
y_one_hot = tf.keras.utils.to_categorical(y_data, num_classes=num_classes)
print(x_one_hot)
print(x_one_hot.shape)
print(y_one_hot)
print(y_one_hot.shape)

[[[1. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 1.]
  [0. 0. 0. 1. 0.]]]
(1, 6, 5)
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [1. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]]
(1, 6, 5)


In [53]:
from tensorflow.keras.models import Model

model = tf.keras.Sequential()
#cell = layers.SimpleRNNCell(units=num_classes, input_shape=(sequence_len, input_dim))
#model.add(layers.RNN(cell=cell, return_sequences=True,return_state=False, input_shape=(sequence_len, input_dim)))

model.add(layers.SimpleRNN(units=100, return_sequences=True,return_state=False,input_shape=(sequence_len, input_dim)))
model.add(layers.TimeDistributed(layers.Dense(units=num_classes, activation='softmax')))

model.compile(loss='categorical_crossentropy', 
              optimizer = tf.keras.optimizers.Adam(learning_rate=learning_rate),
              metrics=['accuracy']
              )

model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_8 (SimpleRNN)     (None, 6, 100)            10600     
_________________________________________________________________
time_distributed_4 (TimeDist (None, 6, 6)              606       
Total params: 11,206
Trainable params: 11,206
Non-trainable params: 0
_________________________________________________________________


In [54]:
model.fit(x_one_hot,y_one_hot,epochs=10)

Epoch 1/10


ValueError: ignored

In [32]:
pred = model.predict(x_one_hot)
pred

array([[[8.6094189e-01, 5.5411991e-02, 4.8132543e-02, 3.3411492e-02,
         2.1020051e-03],
        [6.2979281e-02, 8.7910694e-01, 9.4896654e-04, 1.2875388e-02,
         4.4089533e-02],
        [9.2360896e-01, 5.6576665e-02, 1.0153180e-02, 4.3831649e-03,
         5.2780556e-03],
        [2.3711720e-02, 1.3076218e-03, 9.6074843e-01, 6.5428652e-03,
         7.6892967e-03],
        [1.1363799e-02, 3.0611646e-03, 3.1622755e-03, 9.7402716e-01,
         8.3856834e-03],
        [2.4280949e-03, 8.1333667e-03, 2.9229484e-03, 1.3275799e-02,
         9.7323984e-01]]], dtype=float32)

In [33]:
for i , word in enumerate(pred):
    print(" ".join([idx2char[c] for c in np.argmax(word, axis=1)]))

토 마 토 를 먹 자
