In [1]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



# 1

In [30]:
np.exp([1,2,3,4])/sum(np.exp([1,2,3,4]))

array([0.0320586 , 0.08714432, 0.23688282, 0.64391426])

In [5]:
def softmax(x):
    exp_x = np.exp(x)
    sum_exp_x = sum(exp_x).reshape(-1, 1)
    y = exp_x/sum_exp_x
    return y

In [6]:
print(softmax([2, 1, -1]))

[[0.70538451 0.25949646 0.03511903]]


# 2

In [ ]:
class SoftmaxWithLoss:
    def __init__(self):
        self.loss = None
        self.x = None
        self.y = None
        
    def forward(self, x, t):
        self.t = t
        self.y = softmax(x)
        self.loss = cross_entropy_error(self.y, self.t)
        return self.loss

    def backward(self, dout=1):
        batch_size = self.t.shape[0]
        if self.t.size == self.y.size:
            dx = (self.y - self.t)/batch_size
        else:
            dx = self.y.copy()
            dx[np.arange(batch_size), self.t] -= 1
            dx = dx/batch_size

        return dx

# 3

In [43]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
sentences = ['i love my dog','I love my cat','You love my dog','Do you think my dog is amazing?']

In [44]:
tokenizer = Tokenizer(oov_token = '<oov>')
tokenizer.fit_on_texts(sentences)
tokenizer.word_index

{'<oov>': 1,
 'amazing': 11,
 'cat': 7,
 'do': 8,
 'dog': 4,
 'i': 5,
 'is': 10,
 'love': 3,
 'my': 2,
 'think': 9,
 'you': 6}

In [45]:
max_len = max([ len(line.split()) for line in sentences])
max_len

7

In [46]:
seq = tokenizer.texts_to_sequences(sentences)
padded = pad_sequences(seq, maxlen=max_len, padding = 'post', truncating= 'post')
padded

array([[ 5,  3,  2,  4,  0,  0,  0],
       [ 5,  3,  2,  7,  0,  0,  0],
       [ 6,  3,  2,  4,  0,  0,  0],
       [ 8,  6,  9,  2,  4, 10, 11]], dtype=int32)

# 4

In [39]:
from tensorflow.keras.layers import Dense, LSTM, Dropout, Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.activations import softmax, relu
from tensorflow.keras.losses import categorical_crossentropy, sparse_categorical_crossentropy

In [42]:
vocab_size = 100
embedding_dim = 100
max_len = 40

model = Sequential()
model.add(Embedding(vocab_size, embedding_dim, input_length=max_len))
model.add(LSTM(100))
model.add(Dense(6, activation = 'relu'))
model.add(Dense(6, activation = 'softmax'))
model.compile(loss = 'categorical_crossentropy', optimizer= 'adam', metrics = ['accuracy'])
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 40, 100)           10000     
_________________________________________________________________
lstm_4 (LSTM)                (None, 100)               80400     
_________________________________________________________________
dense_4 (Dense)              (None, 6)                 606       
_________________________________________________________________
dense_5 (Dense)              (None, 6)                 42        
Total params: 91,048
Trainable params: 91,048
Non-trainable params: 0
_________________________________________________________________
